# Generated by Django 5.2.4 on 2025-07-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('car_model', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=20)),
                ('car_capacity', models.PositiveIntegerField()),
                ('license_number', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=10)),
                ('insurance_pollution', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_behaviour', models.IntegerField()),
                ('punctuality', models.IntegerField()),
                ('cleanliness', models.IntegerField()),
                ('payment_issues', models.IntegerField()),
                ('overall_cooperation', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CabVerse.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('ride_type', models.CharField(choices=[('now', 'Now'), ('later', 'Later')], default='now', max_length=10)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('total_passenger', models.PositiveIntegerField(help_text='Total passengers including children')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_taken', to='CabVerse.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_requested', to='CabVerse.rider')),
            ],
        ),
        migrations.CreateModel(
            name='RiderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_experience', models.IntegerField()),
                ('driver_behaviour', models.IntegerField()),
                ('car_cleanliness', models.IntegerField()),
                ('comfort_level', models.IntegerField()),
                ('punctuality', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CabVerse.rider')),
            ],
        ),
    ]
